name: Conventional commit checking ...

on:
  pull_request:
    types: [opened, reopened, ready_for_review]

jobs:
  conventional-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR semantics
        uses: Namchee/conventional-pr@v0.8.0
        with:
          access_token: ${{ secrets.TOKEN_GITHUB }}
          close: false
          issue: false
          body: false
